export const INIT_ALL_POLE = 'INIT_ALL_POLE'
export const INIT_ALL_MODELS = 'INIT_ALL_MODELS'
export const INIT_ALL_MODELS_OTHERS = 'INIT_ALL_MODELS_OTHERS'
//
export const INIT_SHARE_MODELS = 'INIT_SHARE_MODELS'

// 防区
export const INIT_ALL_DEFENCE = 'INIT_ALL_DEFENCE'
export const INIT_ONE_DEFENCE = 'INIT_ONE_DEFENCE'
export const ADD_ONE_DEFENCE = 'ADD_ONE_DEFENCE'
export const DELETE_ONE_DEFENCE = 'DELETE_ONE_DEFENCE'
export const DELETE_ALL_DEFENCE = 'DELETE_ALL_DEFENCE'
export const UPDATE_ONE_DEFENCE = 'UPDATE_ONE_DEFENCE'

